import { pgTable, uuid, varchar, text, timestamp, numeric, integer } from 'drizzle-orm/pg-core';
import { empresas, usuarios } from './core';

// 1. NOTAS FISCAIS DE ENTRADA (Cabeçalho da NF-e Inbound)
export const notasFiscaisEntrada = pgTable('notas_fiscais_entrada', {
  id: uuid('id').primaryKey().defaultRandom(),
  empresaId: uuid('empresa_id').notNull().references(() => empresas.id),
  chaveAcesso: varchar('chave_acesso', { length: 44 }).notNull().unique(),
  numeroDocumento: varchar('numero_documento', { length: 50 }).notNull(),
  serie: varchar('serie', { length: 10 }).notNull().default('1'),
  cnpjEmissor: varchar('cnpj_emissor', { length: 20 }).notNull(),
  razaoSocialEmissor: varchar('razao_social_emissor', { length: 255 }).notNull(),
  inscricaoEstadualEmissor: varchar('inscricao_estadual_emissor', { length: 50 }),
  dataEmissao: timestamp('data_emissao', { withTimezone: true }).notNull(),
  dataEntrada: timestamp('data_entrada', { withTimezone: true }).notNull().defaultNow(),
  valorTotal: numeric('valor_total', { precision: 15, scale: 2 }).notNull(),
  valorProdutos: numeric('valor_produtos', { precision: 15, scale: 2 }).notNull().default('0'),
  valorFrete: numeric('valor_frete', { precision: 15, scale: 2 }).notNull().default('0'),
  valorSeguro: numeric('valor_seguro', { precision: 15, scale: 2 }).notNull().default('0'),
  valorDesconto: numeric('valor_desconto', { precision: 15, scale: 2 }).notNull().default('0'),
  valorOutrasDespesas: numeric('valor_outras_despesas', { precision: 15, scale: 2 }).notNull().default('0'),
  valorIpi: numeric('valor_ipi', { precision: 15, scale: 2 }).notNull().default('0'),
  valorIcms: numeric('valor_icms', { precision: 15, scale: 2 }).notNull().default('0'),
  valorIcmsSt: numeric('valor_icms_st', { precision: 15, scale: 2 }).notNull().default('0'),
  naturezaOperacao: varchar('natureza_operacao', { length: 255 }),
  protocoloAutorizacao: varchar('protocolo_autorizacao', { length: 100 }),
  status: varchar('status', { length: 30 }).notNull().default('AUTORIZADO'),
  tipoEntrada: varchar('tipo_entrada', { length: 30 }).notNull().default('COMPRA_INSUMOS'),
  xmlConteudo: text('xml_conteudo'),
  usuarioId: uuid('usuario_id').references(() => usuarios.id),
  criadoEm: timestamp('criado_em', { withTimezone: true }).notNull().defaultNow(),
  atualizadoEm: timestamp('atualizado_em', { withTimezone: true }).notNull().defaultNow(),
});

// 2. ITENS DA NOTA FISCAL DE ENTRADA
export const nfeItens = pgTable('nfe_itens', {
  id: uuid('id').primaryKey().defaultRandom(),
  empresaId: uuid('empresa_id').notNull().references(() => empresas.id),
  notaFiscalEntradaId: uuid('nota_fiscal_entrada_id').notNull().references(() => notasFiscaisEntrada.id),
  numeroItem: integer('numero_item').notNull(),
  itemId: uuid('item_id'),
  codigoProduto: varchar('codigo_produto', { length: 60 }).notNull(),
  descricaoProduto: varchar('descricao_produto', { length: 255 }).notNull(),
  ncm: varchar('ncm', { length: 10 }),
  cfop: varchar('cfop', { length: 10 }).notNull(),
  unidadeMedida: varchar('unidade_medida', { length: 10 }).notNull(),
  quantidade: numeric('quantidade', { precision: 15, scale: 4 }).notNull(),
  valorUnitario: numeric('valor_unitario', { precision: 15, scale: 4 }).notNull(),
  valorTotalBruto: numeric('valor_total_bruto', { precision: 15, scale: 2 }).notNull(),
  valorDesconto: numeric('valor_desconto', { precision: 15, scale: 2 }).notNull().default('0'),
  valorFreteRateado: numeric('valor_frete_rateado', { precision: 15, scale: 2 }).notNull().default('0'),
  valorSeguroRateado: numeric('valor_seguro_rateado', { precision: 15, scale: 2 }).notNull().default('0'),
  valorOutrasDespesasRateado: numeric('valor_outras_despesas_rateado', { precision: 15, scale: 2 }).notNull().default('0'),
  valorIpi: numeric('valor_ipi', { precision: 15, scale: 2 }).notNull().default('0'),
  valorIcms: numeric('valor_icms', { precision: 15, scale: 2 }).notNull().default('0'),
  valorIcmsSt: numeric('valor_icms_st', { precision: 15, scale: 2 }).notNull().default('0'),
  custoAquisicaoUnitario: numeric('custo_aquisicao_unitario', { precision: 15, scale: 4 }).notNull(),
  custoAquisicaoTotal: numeric('custo_aquisicao_total', { precision: 15, scale: 2 }).notNull(),
  numeroLote: varchar('numero_lote', { length: 50 }),
  loteId: uuid('lote_id'),
  almoxarifadoDestinoId: uuid('almoxarifado_destino_id'),
  criadoEm: timestamp('criado_em', { withTimezone: true }).notNull().defaultNow(),
});

// 3. LEDGER DE MOVIMENTAÇÕES DE ESTOQUE (estoque_movimentacoes)
export const estoqueMovimentacoes = pgTable('estoque_movimentacoes', {
  id: uuid('id').primaryKey().defaultRandom(),
  empresaId: uuid('empresa_id').notNull().references(() => empresas.id),
  itemId: uuid('item_id'),
  almoxarifadoId: uuid('almoxarifado_id'),
  loteId: uuid('lote_id'),
  tipoMovimento: varchar('tipo_movimento', { length: 50 }).notNull(),
  quantidade: numeric('quantidade', { precision: 15, scale: 4 }).notNull(),
  custoUnitario: numeric('custo_unitario', { precision: 15, scale: 4 }).notNull().default('0'),
  custoTotal: numeric('custo_total', { precision: 15, scale: 2 }).notNull().default('0'),
  saldoAnterior: numeric('saldo_anterior', { precision: 15, scale: 4 }).notNull().default('0'),
  saldoPosterior: numeric('saldo_posterior', { precision: 15, scale: 4 }).notNull().default('0'),
  documentoOrigemTipo: varchar('documento_origem_tipo', { length: 50 }).notNull().default('NOTA_FISCAL_ENTRADA'),
  documentoOrigemId: uuid('documento_origem_id'),
  nfeItemId: uuid('nfe_item_id').references(() => nfeItens.id),
  chaveAcessoNfe: varchar('chave_acesso_nfe', { length: 44 }),
  documentoReferencia: varchar('documento_referencia', { length: 100 }),
  motivo: text('motivo'),
  usuarioId: uuid('usuario_id').references(() => usuarios.id),
  criadoEm: timestamp('criado_em', { withTimezone: true }).notNull().defaultNow(),
});
