export interface ModuloDefinition {
  id: string;
  codigo: string;
  nome: string;
  categoria: 'Core' | 'Comercial' | 'Engenharia & PCP' | 'Manufatura' | 'Qualidade & Ativos' | 'Fiscal & Financeiro' | 'Gestão';
  descricao: string;
  entidadesPrincipais: string[];
  isolamentoEmpresa: 'ESTRITO_TRANSACIONAL' | 'COMPARTILHADO_COM_ESCOPO';
  dependenciasInternas: string[];
  dependenciasExternas: string[];
  statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO' | 'AGUARDANDO_DECISAO_ADAPTER';
}

export const MODULOS_ERP: ModuloDefinition[] = [
  {
    id: 'mod-adm',
    codigo: 'ADMINISTRACAO',
    nome: 'Administração & Segurança',
    categoria: 'Core',
    descricao: 'Gestão dos 5 CNPJs, usuários, perfis, matriz RBAC tridimensional e logs de auditoria append-only.',
    entidadesPrincipais: ['Empresa', 'Usuario', 'PerfilAcesso', 'Permissao', 'AuditLog'],
    isolamentoEmpresa: 'COMPARTILHADO_COM_ESCOPO',
    dependenciasInternas: [],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-arquivos',
    codigo: 'ARQUIVOS',
    nome: 'Gestão de Arquivos & Storage de Objetos',
    categoria: 'Core',
    descricao: 'Storage de objetos desacoplado do PostgreSQL com vínculo polimórfico, deduplicação SHA-256, versionamento de desenhos CAD/DXF e auditoria de downloads.',
    entidadesPrincipais: ['Arquivo', 'ArquivoLog', 'ArquivoVersao'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ADMINISTRACAO'],
    dependenciasExternas: ['Object Storage (Local Disk / S3 / MinIO)'],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-crm',
    codigo: 'CRM',
    nome: 'CRM & Prospecção Industrial',
    categoria: 'Comercial',
    descricao: 'Funil de vendas B2B, prospecção de obras, clientes e histórico de interações por empresa.',
    entidadesPrincipais: ['Lead', 'Oportunidade', 'InteracaoCRM', 'EtapaFunil'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ADMINISTRACAO', 'COMERCIAL'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-comercial',
    codigo: 'COMERCIAL',
    nome: 'Gestão Comercial & Clientes',
    categoria: 'Comercial',
    descricao: 'Base de clientes compartilhada, regras de preço por CNPJ, comissões de representantes e metas.',
    entidadesPrincipais: ['Parceiro', 'ParceiroEmpresaInfo', 'TabelaPreco', 'RepresentanteComissao'],
    isolamentoEmpresa: 'COMPARTILHADO_COM_ESCOPO',
    dependenciasInternas: ['ADMINISTRACAO'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-orcamento',
    codigo: 'ORCAMENTO',
    nome: 'Orçamento Técnico & Formação de Preço',
    categoria: 'Comercial',
    descricao: 'Cálculo de custo de corte, dobra, horas-máquina, consumo de aço, margens e simulação de impostos.',
    entidadesPrincipais: ['Orcamento', 'OrcamentoItem', 'ComposicaoCustoOrcamento'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['COMERCIAL', 'ENGENHARIA', 'ESTOQUE'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-pedido',
    codigo: 'PEDIDO',
    nome: 'Pedidos de Venda',
    categoria: 'Comercial',
    descricao: 'Gestão do ciclo de vida dos pedidos, integração intercompany espelhada e liberação para PCP.',
    entidadesPrincipais: ['PedidoVenda', 'PedidoVendaItem', 'HistoricoStatusPedido'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ORCAMENTO', 'CREDITO_SERASA', 'PCP', 'FINANCEIRO', 'FISCAL'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-credito',
    codigo: 'CREDITO_SERASA',
    nome: 'Análise de Crédito & Serasa',
    categoria: 'Fiscal & Financeiro',
    descricao: 'Alçadas de aprovação, política de crédito interna e adapter para bureau de crédito Serasa.',
    entidadesPrincipais: ['AnaliseCredito', 'PoliticaCredito', 'HistoricoConsultasBureau'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['COMERCIAL', 'FINANCEIRO'],
    dependenciasExternas: ['Serasa / Boa Vista (TODO / decision-needed)'],
    statusIntegracao: 'AGUARDANDO_DECISAO_ADAPTER',
  },
  {
    id: 'mod-engenharia',
    codigo: 'ENGENHARIA',
    nome: 'Engenharia de Produto & BOM',
    categoria: 'Engenharia & PCP',
    descricao: 'Estruturas de produto multinível (BOM), roteiros de fabricação, centros de trabalho e arquivos CAD/DXF.',
    entidadesPrincipais: ['EngenhariaBOM', 'EngenhariaBOMItem', 'RoteiroFabricacao', 'CentroTrabalho', 'ArquivoTecnico'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ADMINISTRACAO', 'ESTOQUE'],
    dependenciasExternas: ['Object Storage (TODO / decision-needed)'],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-estoque',
    codigo: 'ESTOQUE',
    nome: 'Estoque, Almoxarifado & Lotes',
    categoria: 'Engenharia & PCP',
    descricao: 'Saldos por almoxarifado, controle de corridas/lotes de aço com certificados de usina e movimentações imutáveis.',
    entidadesPrincipais: ['Item', 'ItemEmpresaConfig', 'Almoxarifado', 'Lote', 'SaldoEstoque', 'MovimentacaoEstoque'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ADMINISTRACAO'],
    dependenciasExternas: ['Object Storage (Certificados de Usina)'],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-compras',
    codigo: 'COMPRAS',
    nome: 'Compras & Suprimentos',
    categoria: 'Engenharia & PCP',
    descricao: 'Requisições de compras, mapa de cotação de matéria-prima, ordens de compra e aprovações.',
    entidadesPrincipais: ['RequisicaoCompra', 'CotacaoFornecedor', 'OrdemCompra', 'OrdemCompraItem'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PCP', 'ESTOQUE', 'FINANCEIRO'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-pcp',
    codigo: 'PCP',
    nome: 'PCP (Planejamento e Controle da Produção)',
    categoria: 'Engenharia & PCP',
    descricao: 'Plano Mestre de Produção (MPS), cálculo de necessidades líquidas (MRP I) e sequenciamento de fábrica.',
    entidadesPrincipais: ['PlanoMestreProducao', 'NecessidadeMaterialMRP', 'CargaMaquina'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PEDIDO', 'ENGENHARIA', 'ESTOQUE', 'PRODUCAO'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-producao',
    codigo: 'PRODUCAO',
    nome: 'Chão de Fábrica & OPs',
    categoria: 'Manufatura',
    descricao: 'Emissão e execução de Ordens de Produção (OPs), apontamentos de tempo, refugo e encerramento.',
    entidadesPrincipais: ['OrdemProducao', 'ApontamentoProducao', 'MotivoParada', 'FechamentoCustoOP'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PCP', 'ENGENHARIA', 'ESTOQUE', 'QUALIDADE'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-corte',
    codigo: 'CORTE',
    nome: 'Corte a Laser, Plasma & Oxicorte',
    categoria: 'Manufatura',
    descricao: 'Ordens de corte de chapas, gestão de aproveitamento, retalhos/sobras úteis catalogadas com QR Code.',
    entidadesPrincipais: ['OrdemCorte', 'PlanoCorteNesting', 'RetalhoGerado'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PRODUCAO', 'ESTOQUE'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-dobra',
    codigo: 'DOBRA',
    nome: 'Dobra CNC & Conformação',
    categoria: 'Manufatura',
    descricao: 'Ordens de dobra CNC, controle de matrizes/punções, sequência de dobras e tolerâncias dimensionais.',
    entidadesPrincipais: ['OrdemDobra', 'ProgramaDobraCNC', 'FerramentalDobra'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PRODUCAO', 'ENGENHARIA'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-servicos',
    codigo: 'SERVICOS',
    nome: 'Serviços Industriais & Montagem',
    categoria: 'Manufatura',
    descricao: 'Ordens de Serviço (OS) para obras civis/industriais, caldeiraria em campo e locação de equipes.',
    entidadesPrincipais: ['OrdemServico', 'ApontamentoHoraOS', 'DespesaReembolsavelOS'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ADMINISTRACAO', 'FINANCEIRO', 'FISCAL'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-qualidade',
    codigo: 'QUALIDADE',
    nome: 'Gestão da Qualidade & RNC',
    categoria: 'Qualidade & Ativos',
    descricao: 'Inspeção de recebimento de chapas/perfis, rastreabilidade de certificados e Relatórios de Não Conformidade.',
    entidadesPrincipais: ['InspecaoQualidade', 'RNC_NaoConformidade', 'PlanoAcaoCorretiva'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ESTOQUE', 'PRODUCAO', 'COMPRAS'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-manutencao',
    codigo: 'MANUTENCAO',
    nome: 'Manutenção Industrial (TPM)',
    categoria: 'Qualidade & Ativos',
    descricao: 'Planos de manutenção preventiva, ordens de serviço corretivas em máquinas e indicadores MTBF/MTTR.',
    entidadesPrincipais: ['PlanoManutencao', 'OrdemManutencao', 'HistoricoIntervencoes'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PRODUCAO', 'ESTOQUE'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-expedicao',
    codigo: 'EXPEDICAO',
    nome: 'Expedição & Logística de Cargas',
    categoria: 'Qualidade & Ativos',
    descricao: 'Romaneios de entrega, conferência por pesagem, agendamento de coletas e controle de transportadoras.',
    entidadesPrincipais: ['RomaneioExpedicao', 'ItemRomaneio', 'ConferenciaCarga'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PEDIDO', 'PRODUCAO', 'FISCAL'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-fiscal',
    codigo: 'FISCAL',
    nome: 'Fiscal & Documentos Eletrônicos',
    categoria: 'Fiscal & Financeiro',
    descricao: 'Motor de regras tributárias, emissão de NF-e, NFS-e, MDF-e, entrada de XMLs e auditoria de impostos.',
    entidadesPrincipais: ['DocumentoFiscal', 'DocumentoFiscalItem', 'RegraTributariaCFOP', 'ApuracaoImpostos'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PEDIDO', 'SERVICOS', 'COMPRAS', 'FINANCEIRO'],
    dependenciasExternas: ['Provedor SEFAZ / Prefeituras (TODO / decision-needed)'],
    statusIntegracao: 'AGUARDANDO_DECISAO_ADAPTER',
  },
  {
    id: 'mod-financeiro',
    codigo: 'FINANCEIRO',
    nome: 'Financeiro, AP/AR & Tesouraria',
    categoria: 'Fiscal & Financeiro',
    descricao: 'Contas a pagar, contas a receber, fluxo de caixa diário projetado, conciliação bancária e boletos/CNAB.',
    entidadesPrincipais: ['TituloReceber', 'TituloPagar', 'MovimentacaoBancaria', 'BoletoBancario', 'ContaBancaria'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PEDIDO', 'COMPRAS', 'FISCAL'],
    dependenciasExternas: ['Bancos CNAB/APIs (TODO / decision-needed)'],
    statusIntegracao: 'AGUARDANDO_DECISAO_ADAPTER',
  },
  {
    id: 'mod-rh',
    codigo: 'RH_OPERACIONAL',
    nome: 'RH Operacional & Segurança Fabril',
    categoria: 'Gestão',
    descricao: 'Cadastro de operadores técnicos, alocação em centros de custo, controle de EPIs e certificações NR-12/NR-35.',
    entidadesPrincipais: ['FuncionarioOperacional', 'EntregaEPI', 'TreinamentoNormativo'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ADMINISTRACAO', 'PRODUCAO'],
    dependenciasExternas: ['CCT Sindicatos (TODO / decision-needed)'],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-bi',
    codigo: 'BI',
    nome: 'BI & Indicadores Industriais',
    categoria: 'Gestão',
    descricao: 'Consolidação de DRE gerencial, OEE por máquina, faturamento por empresa do grupo e rentabilidade por cliente.',
    entidadesPrincipais: ['IndicadorOEE', 'ConsolidadoGerencialGrupo', 'MetricaRentabilidade'],
    isolamentoEmpresa: 'COMPARTILHADO_COM_ESCOPO',
    dependenciasInternas: ['FINANCEIRO', 'PRODUCAO', 'COMERCIAL', 'ESTOQUE'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
];
