export interface ModuloDefinition {
  id: string;
  codigo: string;
  nome: string;
  categoria: 'Core' | 'Comercial' | 'Engenharia & PCP' | 'Manufatura' | 'Qualidade & Ativos' | 'Fiscal & Financeiro' | 'Gestão';
  descricao: string;
  entidadesPrincipais: string[];
  isolamentoEmpresa: 'ESTRITO_TRANSACIONAL' | 'COMPARTILHADO_COM_ESCOPO';
  dependenciasInternas: string[];
  dependenciasExternas: string[];
  statusIntegracao: 'IMPLEMENTADO' | 'PRONTO_PARA_IMPLEMENTACAO' | 'AGUARDANDO_DECISAO_ADAPTER';
}

export const MODULOS_ERP: ModuloDefinition[] = [
  {
    id: 'mod-adm',
    codigo: 'ADMINISTRACAO',
    nome: 'Administração & Segurança',
    categoria: 'Core',
    descricao: 'Gestão dos 5 CNPJs, usuários, perfis, matriz RBAC tridimensional e logs de auditoria append-only.',
    entidadesPrincipais: ['Empresa', 'Usuario', 'PerfilAcesso', 'Permissao', 'AuditLog'],
    isolamentoEmpresa: 'COMPARTILHADO_COM_ESCOPO',
    dependenciasInternas: [],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-arquivos',
    codigo: 'ARQUIVOS',
    nome: 'Gestão de Arquivos & Storage de Objetos',
    categoria: 'Core',
    descricao: 'Storage de objetos desacoplado do PostgreSQL com vínculo polimórfico, deduplicação SHA-256, versionamento de desenhos CAD/DXF e auditoria de downloads.',
    entidadesPrincipais: ['Arquivo', 'ArquivoLog', 'ArquivoVersao'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ADMINISTRACAO'],
    dependenciasExternas: ['Object Storage (Local Disk / S3 / MinIO)'],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-crm',
    codigo: 'CRM',
    nome: 'CRM & Prospecção Industrial',
    categoria: 'Comercial',
    descricao: 'Funil de vendas B2B, prospecção de obras, clientes e histórico de interações por empresa.',
    entidadesPrincipais: ['Lead', 'Oportunidade', 'InteracaoCRM', 'EtapaFunil'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ADMINISTRACAO', 'COMERCIAL'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-comercial',
    codigo: 'COMERCIAL',
    nome: 'Gestão Comercial & Clientes',
    categoria: 'Comercial',
    descricao: 'Base de clientes compartilhada, regras de preço por CNPJ, comissões de representantes e metas.',
    entidadesPrincipais: ['Parceiro', 'ParceiroEmpresaInfo', 'TabelaPreco', 'RepresentanteComissao'],
    isolamentoEmpresa: 'COMPARTILHADO_COM_ESCOPO',
    dependenciasInternas: ['ADMINISTRACAO'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-orcamento',
    codigo: 'ORCAMENTO',
    nome: 'Orçamento Técnico & Formação de Preço (CPQ)',
    categoria: 'Comercial',
    descricao: 'CPQ industrial completo para produto pronto, fabricado (corte laser/plasma, dobra CNC, solda MIG/TIG, pintura, montagem), serviço puro e produto+serviço com parametrização dinâmica de CHM, GGF, tributos, alçadas e versionamento.',
    entidadesPrincipais: ['Orcamento', 'OrcamentoVersao', 'OrcamentoItem', 'OrcamentoCusto', 'RegraDesconto', 'RegraAprovacao', 'HistoricoNegociacao'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['COMERCIAL', 'ENGENHARIA', 'ARQUIVOS', 'ADMINISTRACAO'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-pedido',
    codigo: 'PEDIDO',
    nome: 'Pedidos de Venda',
    categoria: 'Comercial',
    descricao: 'Gestão do ciclo de vida dos pedidos, integração intercompany espelhada e liberação para PCP.',
    entidadesPrincipais: ['PedidoVenda', 'PedidoVendaItem', 'HistoricoStatusPedido'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ORCAMENTO', 'CREDITO_SERASA', 'PCP', 'FINANCEIRO', 'FISCAL'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-credito',
    codigo: 'CREDITO_SERASA',
    nome: 'Análise de Crédito & Serasa',
    categoria: 'Fiscal & Financeiro',
    descricao: 'Alçadas de aprovação, política de crédito interna e adapter para bureau de crédito Serasa.',
    entidadesPrincipais: ['AnaliseCredito', 'PoliticaCredito', 'HistoricoConsultasBureau'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['COMERCIAL', 'FINANCEIRO'],
    dependenciasExternas: ['Serasa / Boa Vista (TODO / decision-needed)'],
    statusIntegracao: 'AGUARDANDO_DECISAO_ADAPTER',
  },
  {
    id: 'mod-engenharia',
    codigo: 'ENGENHARIA',
    nome: 'Engenharia de Produto & Processos (BOM/Roteiros)',
    categoria: 'Engenharia & PCP',
    descricao: 'Gestão de projetos industriais, controle imutável de revisões/versões, lista de materiais (BOM) com cálculo de perdas técnicas e nesting, roteiros de fabricação com tempos padrão, anexos CAD/CAM e rastreabilidade estrita de OPs.',
    entidadesPrincipais: ['Projeto', 'ProjetoRevisao', 'EstruturaProduto', 'EstruturaItem', 'Roteiro', 'RoteiroOperacao', 'ArquivoTecnico', 'OrdemProducaoVinculo'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ADMINISTRACAO', 'ESTOQUE', 'PCP'],
    dependenciasExternas: ['Object Storage (CAD/CAM DXF, STEP, PDF)'],
    statusIntegracao: 'IMPLEMENTADO',
  },
  {
    id: 'mod-estoque',
    codigo: 'ESTOQUE',
    nome: 'Estoque, Almoxarifado & Lotes',
    categoria: 'Engenharia & PCP',
    descricao: 'Saldos por almoxarifado, controle de corridas/lotes de aço com certificados de usina e movimentações imutáveis.',
    entidadesPrincipais: ['Item', 'ItemEmpresaConfig', 'Almoxarifado', 'Lote', 'SaldoEstoque', 'MovimentacaoEstoque'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ADMINISTRACAO'],
    dependenciasExternas: ['Object Storage (Certificados de Usina)'],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-compras',
    codigo: 'COMPRAS',
    nome: 'Compras & Suprimentos',
    categoria: 'Engenharia & PCP',
    descricao: 'Requisições de compras, mapa de cotação de matéria-prima, ordens de compra e aprovações.',
    entidadesPrincipais: ['RequisicaoCompra', 'CotacaoFornecedor', 'OrdemCompra', 'OrdemCompraItem'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PCP', 'ESTOQUE', 'FINANCEIRO'],
    dependenciasExternas: [],
    statusIntegracao: 'IMPLEMENTADO',
  },
  {
    id: 'mod-pcp',
    codigo: 'PCP',
    nome: 'PCP (Planejamento e Controle da Produção)',
    categoria: 'Engenharia & PCP',
    descricao: 'Plano Mestre de Produção (MPS), cálculo de necessidades líquidas (MRP I) e sequenciamento de fábrica.',
    entidadesPrincipais: ['PlanoMestreProducao', 'NecessidadeMaterialMRP', 'CargaMaquina'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PEDIDO', 'ENGENHARIA', 'ESTOQUE', 'PRODUCAO'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-producao',
    codigo: 'PRODUCAO',
    nome: 'Chão de Fábrica & OPs',
    categoria: 'Manufatura',
    descricao: 'Emissão e execução de Ordens de Produção (OPs), apontamentos de tempo, refugo e encerramento.',
    entidadesPrincipais: ['OrdemProducao', 'ApontamentoProducao', 'MotivoParada', 'FechamentoCustoOP'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PCP', 'ENGENHARIA', 'ESTOQUE', 'QUALIDADE'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-corte',
    codigo: 'CORTE',
    nome: 'Corte a Laser, Plasma & Oxicorte',
    categoria: 'Manufatura',
    descricao: 'Ordens de corte de chapas, gestão de aproveitamento, retalhos/sobras úteis catalogadas com QR Code.',
    entidadesPrincipais: ['OrdemCorte', 'PlanoCorteNesting', 'RetalhoGerado'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PRODUCAO', 'ESTOQUE'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-dobra',
    codigo: 'DOBRA',
    nome: 'Dobra CNC & Conformação',
    categoria: 'Manufatura',
    descricao: 'Ordens de dobra CNC, controle de matrizes/punções, sequência de dobras e tolerâncias dimensionais.',
    entidadesPrincipais: ['OrdemDobra', 'ProgramaDobraCNC', 'FerramentalDobra'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PRODUCAO', 'ENGENHARIA'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-servicos',
    codigo: 'SERVICOS',
    nome: 'Serviços Industriais & Montagem',
    categoria: 'Manufatura',
    descricao: 'Ordens de Serviço (OS) para obras civis/industriais, caldeiraria em campo e locação de equipes.',
    entidadesPrincipais: ['OrdemServico', 'ApontamentoHoraOS', 'DespesaReembolsavelOS'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ADMINISTRACAO', 'FINANCEIRO', 'FISCAL'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-qualidade',
    codigo: 'QUALIDADE',
    nome: 'Gestão da Qualidade & RNC (ISO 9001)',
    categoria: 'Qualidade & Ativos',
    descricao: 'Inspeções de recebimento, em processo e final, modelos de checklist com tolerâncias, Não Conformidades (RNC/8D) com Ishikawa 6M e 5 Porquês, planos de ação preventiva/corretiva, ordens de retrabalho, gestão de sucatas e apuração do Custo da Não Qualidade (CNQ).',
    entidadesPrincipais: [
      'ModeloChecklist',
      'ItemChecklist',
      'InspecaoQualidade',
      'RespostaInspecao',
      'NaoConformidade',
      'CausaIshikawa',
      'AcaoCorretiva',
      'AcaoPreventiva',
      'RetrabalhoQualidade',
      'RefugoQualidade',
      'IndicadoresCNQ',
    ],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ESTOQUE', 'PRODUCAO', 'COMPRAS', 'ENGENHARIA'],
    dependenciasExternas: [],
    statusIntegracao: 'IMPLEMENTADO',
  },
  {
    id: 'mod-manutencao',
    codigo: 'MANUTENCAO',
    nome: 'Manutenção & Gestão de Ativos (PCM)',
    categoria: 'Qualidade & Ativos',
    descricao: 'Gestão completa de ativos industriais, componentes, planos preventivos/preditivos, OMs corretivas com bloqueio de PCP, telemetria preditiva IoT, horímetros, catálogo de falhas ISO 14224, requisição de sobressalentes com compra automática, serviços de terceiros, ferramentas/matrizes e indicadores MTBF, MTTR, Disponibilidade e Custo/Hora.',
    entidadesPrincipais: [
      'AtivoIndustrial',
      'ComponenteAtivo',
      'PlanoManutencao',
      'OrdemManutencao',
      'FalhaCatalogo',
      'ParadaManutencao',
      'ManutencaoItemRequisitado',
      'ManutencaoServicoTerceiro',
      'RegistroHorimetro',
      'FerramentaIndustrial',
      'MovimentoFerramenta',
      'IndicadoresPCM',
    ],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PRODUCAO', 'ESTOQUE', 'COMPRAS', 'PCP', 'QUALIDADE'],
    dependenciasExternas: ['Telemetria IoT / CLP (Sensores)'],
    statusIntegracao: 'IMPLEMENTADO',
  },
  {
    id: 'mod-expedicao',
    codigo: 'EXPEDICAO',
    nome: 'Expedição & Logística de Cargas',
    categoria: 'Qualidade & Ativos',
    descricao: 'Romaneios de entrega, conferência por pesagem, agendamento de coletas e controle de transportadoras.',
    entidadesPrincipais: ['RomaneioExpedicao', 'ItemRomaneio', 'ConferenciaCarga'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PEDIDO', 'PRODUCAO', 'FISCAL'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-fiscal',
    codigo: 'FISCAL',
    nome: 'Fiscal & Documentos Eletrônicos (NF-e/NFS-e/IBS-CBS)',
    categoria: 'Fiscal & Financeiro',
    descricao: 'Camada fiscal desacoplada com isolamento multiempresa, motor tributário parametrizado (ICMS, IPI, PIS, COFINS, ISS e extensão IBS/CBS Reforma Tributária), séries/numerações atômicas, eventos fiscais (CC-e/Cancelamento), certificados A1 e adapters SEFAZ/NFS-e com logs de auditoria e idempotência.',
    entidadesPrincipais: [
      'configuracoes_fiscais',
      'regras_tributarias',
      'operacoes_fiscais',
      'tributacoes_produtos',
      'tributacoes_servicos',
      'series_fiscais',
      'numeracoes_fiscais',
      'documentos_fiscais',
      'documentos_fiscais_itens',
      'eventos_fiscais',
      'certificados_referencias',
      'integrações_fiscais',
    ],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PEDIDO', 'SERVICOS', 'COMPRAS', 'FINANCEIRO', 'EXPEDICAO'],
    dependenciasExternas: ['Provedor SEFAZ (Adapter/Mock)', 'Prefeituras NFS-e (Adapter/Mock)'],
    statusIntegracao: 'IMPLEMENTADO',
  },
  {
    id: 'mod-financeiro',
    codigo: 'FINANCEIRO',
    nome: 'Financeiro, Bancário & Cobrança (AP/AR & Adapters)',
    categoria: 'Fiscal & Financeiro',
    descricao: 'Gestão multiempresa de Contas a Pagar/Receber, conciliação de extratos, tesouraria, caixas fabris, emissão e registro de boletos híbridos e cobranças PIX EMV com arquitetura BillingProvider/Adapters (Itaú, BB, Bradesco, Santander, Sicoob e Mock).',
    entidadesPrincipais: [
      'contas_bancarias',
      'configuracoes_cobranca',
      'cobrancas',
      'cobranca_eventos',
      'movimentos_financeiros',
      'caixas',
      'titulos_receber',
      'titulos_pagar',
    ],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['PEDIDO', 'COMPRAS', 'FISCAL', 'ADMINISTRACAO'],
    dependenciasExternas: ['BillingProvider / BancoAdapter (Itaú, BB, Bradesco, Santander, Sicoob, Mock)'],
    statusIntegracao: 'IMPLEMENTADO',
  },
  {
    id: 'mod-rh',
    codigo: 'RH_OPERACIONAL',
    nome: 'RH Operacional & Segurança Fabril',
    categoria: 'Gestão',
    descricao: 'Cadastro de operadores técnicos, alocação em centros de custo, controle de EPIs e certificações NR-12/NR-35.',
    entidadesPrincipais: ['FuncionarioOperacional', 'EntregaEPI', 'TreinamentoNormativo'],
    isolamentoEmpresa: 'ESTRITO_TRANSACIONAL',
    dependenciasInternas: ['ADMINISTRACAO', 'PRODUCAO'],
    dependenciasExternas: ['CCT Sindicatos (TODO / decision-needed)'],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
  {
    id: 'mod-bi',
    codigo: 'BI',
    nome: 'BI & Indicadores Industriais',
    categoria: 'Gestão',
    descricao: 'Consolidação de DRE gerencial, OEE por máquina, faturamento por empresa do grupo e rentabilidade por cliente.',
    entidadesPrincipais: ['IndicadorOEE', 'ConsolidadoGerencialGrupo', 'MetricaRentabilidade'],
    isolamentoEmpresa: 'COMPARTILHADO_COM_ESCOPO',
    dependenciasInternas: ['FINANCEIRO', 'PRODUCAO', 'COMERCIAL', 'ESTOQUE'],
    dependenciasExternas: [],
    statusIntegracao: 'PRONTO_PARA_IMPLEMENTACAO',
  },
];
